# Generated by Django 3.2.7 on 2021-10-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkooPalaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_hyvaa', models.TextField(max_length=1000)),
                ('t_huonoa', models.TextField(max_length=1000)),
                ('t_kehitettavaa', models.TextField(max_length=1000)),
                ('arvosana', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('kayttaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KokousPalaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_hyvaa', models.TextField(max_length=1000)),
                ('k_huonoa', models.TextField(max_length=1000)),
                ('k_kehitettavaa', models.TextField(max_length=1000)),
                ('arvosana', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('kayttaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hairioilmoitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_huoneisto', models.TextField(max_length=1000)),
                ('h_hairionkuvaus', models.TextField(max_length=1000)),
                ('h_hairiontarkennus', models.TextField(max_length=1000)),
                ('arvosana', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('kayttaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
